### ISSUE TITLE
radio open to talk

### ISSUE THREAD

**Issue by tirna-eirl** [FrazzIe/rp-radio#13]
Hello,
I come to you to know if it is possible to remove the verification 'Radio.Open' to be able to speak without having the radio open

**Comment by Vestedmarius** [comment]
take a look at the config and set `AllowRadioWhenClosed` to true

**Comment by tirna-eirl** [comment]
actually I have badly looked at the documentation!
sorry for inconvenience ..

congratulations for your system is really complete!
