### ISSUE TITLE
Radio Noise, No audio transmission

### ISSUE THREAD

**Issue by aidenszolosi** [FrazzIe/rp-radio#16]
I disabled all my other voice chat plugins other than mumble and rp-radio. Mumble seems to work great, but RP-radio doesnt. All I hear is the click in and out of other players talking. The voice isnt transmitting, but the radio registers that someone is broadcasting
Thanks!.

**Comment by aidenszolosi** [comment]
Also, there isn't a server script associated with this?? Is it necessary to keep that in the fxmanifest?

**Comment by Asger2** [comment]
do you had fixet it @aidenszolosi

**Comment by aidenszolosi** [comment]
> do you had fixet it @aidenszolosi

Nope.

**Comment by FrazzIe** [comment]
move to #17
