### ISSUE TITLE
Radio installed and reacting but no transmitting

### ISSUE THREAD

**Issue by SyalFett** [FrazzIe/rp-radio#17]
So we got it installed and configured but it wont transfer the voice at all.
someone said it might be due to the fivem updates lately. We try to get it running since 3  days already but nothing helped so far, we also tried downgrading but still wont work.

**Comment by aidenszolosi** [comment]
Setting voice_use2dAudio to 1 might fix it.

--- From frazzle over on fivem forums

**Comment by SyalFett** [comment]
Well it does not help, like i said the generel mumble-voip works only the rdio is not working, we hear the sound but the voice does not get transmittet

**Comment by FrazzIe** [comment]
`mumble-voip` is responsible for transmitting voices not `rp-radio`. This issue will be fixed when i'm finished refactoring `mumble-voip`. You can view my progress on the `dev` branch https://github.com/FrazzIe/mumble-voip/tree/dev
