### ISSUE TITLE
RP-Radio HUD 

### ISSUE THREAD

**Issue by PurchasedGaming** [FrazzIe/rp-radio#18]
Hello,

When trying to use the Radio when Clicking "Shift + F2" The Hud doesn't show as the following:
![image](https://user-images.githubusercontent.com/51837015/88802441-fc898700-d1a2-11ea-9221-06b52032e59e.png)

Furthermore, When talking is this supposed to be highlighted, if not, what do I do around this? 
![image](https://user-images.githubusercontent.com/51837015/88802525-17f49200-d1a3-11ea-9566-b7fdda3fa9fe.png)

Thank you,
Kieran

**Comment by PurchasedGaming** [comment]
The second image in the bottom right is the highlighted bit.

**Comment by YInfeRnal** [comment]
i have same.

**Comment by YInfeRnal** [comment]
thr radio work fine but HUD not working...
