### ISSUE TITLE
Private

### ISSUE THREAD

**Issue by IThinkImGood** [FrazzIe/rp-radio#22]
Hey guys,

I have the issue that i want the rp-radio to be only private for cops, EMS etc.
Do you guys know how i tried to add a item and setting has on false

but do you guys know how?

**Comment by iSentrie** [comment]
Frequency = {
        Private = { -- List of private frequencies
            [1] = true, -- Make 1 a private frequency
            [2] = true,
        }, -- List of private frequencies

**Comment by Timmyopp** [comment]
Yeah, but as police or EMS i can't join those frequency.
Is there any place inside config.lua to add job names?

**Comment by FrazzIe** [comment]
use the exports
