### ISSUE TITLE
Exports not working

### ISSUE THREAD

**Issue by DonJoan** [FrazzIe/rp-radio#29]
have a problem accessing the private frequencies.
I use es_extended v1 final for my server and latest esx scripts .
Server artifacts 2949

I have added the necessary lines to the policejob but I still do not have access

Fix?

**Comment by rhapidfyre** [comment]
I have written my own script, and have this same problem. The exports do nothing. I added a bunch of commands to see the value of all the getters, and they all return false and setting everything to true and giving them access to various frequencies.

Dead in the water.

**Comment by DonJoan** [comment]
My idea was to create code to access through a command








 -------- Оригинално писмо --------

От: Michael Harris notifications@github.com

Относно: Re: [FrazzIe/rp-radio] Exports not working (#29)

До: FrazzIe/rp-radio  

Изпратено на: 01.12.2020 03:03



 
 
  
  
  
I have written my own script, and have this same problem. The exports do nothing. I added a bunch of commands to see the value of all the getters, and they all return false and setting everything to true and giving them access to various frequencies.  
  
Dead in the water.

**Comment by DonJoan** [comment]
In that case, how will it be fixed 
I also tried in many different ways I tried to create a script that gives permission but still do not have access










 -------- Оригинално писмо --------

От: Michael Harris notifications@github.com

Относно: Re: [FrazzIe/rp-radio] Exports not working (#29)

До: FrazzIe/rp-radio  

Изпратено на: 01.12.2020 03:03



 
 
  
  
  
I have written my own script, and have this same problem. The exports do nothing. I added a bunch of commands to see the value of all the getters, and they all return false and setting everything to true and giving them access to various frequencies.  
  
Dead in the water.
