### ISSUE TITLE
/radio - does nothing

### ISSUE THREAD

**Issue by iSentrie** [FrazzIe/rp-radio#3]
Hey, why when I type /radio it does nothing?

**Comment by kFxDaKing** [comment]
Same problem

**Comment by kFxDaKing** [comment]
Classic voice chat works, but radio dont

**Comment by termanator1128** [comment]
@XvenDeR @wolgix Make sure you use the export/function to enable the radio for yourself.

**Comment by iSentrie** [comment]
hmmm i did added the permission for frequency, but probably not the enable one.

**Comment by FrazzIe** [comment]
by default the radio is disabled (its meant to be used as an in-game item) to give players the radio by default in the client.lua at the top change Radio.Has to true, if you would like to make it an item look at the replies in the FiveM forums, there is a tutorial for adding it as an ESX item.

The export that is used to give/take a players radio is `exports:["rp-radio"]:SetRadio(true/false)` or the event `Radio.Set`
