### ISSUE TITLE
ace permissions?

### ISSUE THREAD

**Issue by rahafuf** [FrazzIe/rp-radio#32]
i installed rp-radio and trying to get certain channels locked to ace access but its not seeing them for some reason. this is how i have it set up

```
if ESX.PlayerData.job.name == 'police' then 
        exports["rp-radio"]:GivePlayerAccessToFrequencies(1)
    elseif ESX.PlayerData.job.name == 'police' and IsPlayerAceAllowed(source, "group.admin") then --Owners Channel
        exports["rp-radio"]:GivePlayerAccessToFrequencies(2)
    elseif ESX.PlayerData.job.name == 'police' and IsPlayerAceAllowed(source, "group.pshigh") then --High Command Channel
        exports["rp-radio"]:GivePlayerAccessToFrequencies(3)
    elseif ESX.PlayerData.job.name == 'police' and IsPlayerAceAllowed(source, "group.swat") then --Swat Channel
        exports["rp-radio"]:GivePlayerAccessToFrequencies(4)        
    elseif ESX.PlayerData.job.name == 'ambulance' and IsPlayerAceAllowed(source, "group.ems") then--[To add a job copy the from here]
        exports["rp-radio"]:GivePlayerAccessToFrequencies(1, 2)--[to here] and paste it right blow
    elseif PlayerData.job and ESX.PlayerData.job.name == 'mechanic' then -- here then rename 'mechanic' to the job name
        exports["rp-radio"]:GivePlayerAccessToFrequencies(4) -- set radio freq here (9, 10)
    else--(Do not remove due to this will remove it from everyone one else without or being set to another job)
        exports["rp-radio"]:RemovePlayerAccessToFrequencies(1, 2, 3, 4)--(Dont Touch)
    end --(Dont Touch)
```

ive got the groups called in vMenu. i know they are working cuz we use it for spawning cars in vmenu

**Comment by AndrewBarham** [comment]
> i installed rp-radio and trying to get certain channels locked to ace access but its not seeing them for some reason. this is how i have it set up
> 
> ```
> if ESX.PlayerData.job.name == 'police' then 
>         exports["rp-radio"]:GivePlayerAccessToFrequencies(1)
>     elseif ESX.PlayerData.job.name == 'police' and IsPlayerAceAllowed(source, "group.admin") then --Owners Channel
>         exports["rp-radio"]:GivePlayerAccessToFrequencies(2)
>     elseif ESX.PlayerData.job.name == 'police' and IsPlayerAceAllowed(source, "group.pshigh") then --High Command Channel
>         exports["rp-radio"]:GivePlayerAccessToFrequencies(3)
>     elseif ESX.PlayerData.job.name == 'police' and IsPlayerAceAllowed(source, "group.swat") then --Swat Channel
>         exports["rp-radio"]:GivePlayerAccessToFrequencies(4)        
>     elseif ESX.PlayerData.job.name == 'ambulance' and IsPlayerAceAllowed(source, "group.ems") then--[To add a job copy the from here]
>         exports["rp-radio"]:GivePlayerAccessToFrequencies(1, 2)--[to here] and paste it right blow
>     elseif PlayerData.job and ESX.PlayerData.job.name == 'mechanic' then -- here then rename 'mechanic' to the job name
>         exports["rp-radio"]:GivePlayerAccessToFrequencies(4) -- set radio freq here (9, 10)
>     else--(Do not remove due to this will remove it from everyone one else without or being set to another job)
>         exports["rp-radio"]:RemovePlayerAccessToFrequencies(1, 2, 3, 4)--(Dont Touch)
>     end --(Dont Touch)
> ```
> 
> ive got the groups called in vMenu. i know they are working cuz we use it for spawning cars in vmenu

Did you ever figure out how to do this?
