### ISSUE TITLE
Exports

### ISSUE THREAD

**Issue by KingMacking** [FrazzIe/rp-radio#40]
So, they work everywhere but no on policejob, any idea why ?
The problem is that police cant go inside to their private frequencies channels.
![imagen](https://user-images.githubusercontent.com/36141440/104430650-b748ee00-5565-11eb-8e3a-c890e7633b1f.png)
These are my exports on police job, i have been searching another way to do it but didnt' find anything.
Hope there's a fix for this :(

**Comment by DonJoan** [comment]
Apparently the creator doesn't care much because I've written to him several times.

I know the solution to this problem and you can write to me in discord to tell you 
My discord : 😈_DonJoan_😈#8207

**Comment by KingMacking** [comment]
> 
> 
> Apparently the creator doesn't care much because I've written to him several times.
> 
> I know the solution to this problem and you can write to me in discord to tell you
> My discord : 😈_DonJoan_😈#8207

Just write it here lol

**Comment by Yours-Truely** [comment]
> Apparently the creator doesn't care much because I've written to him several times.
> 
> I know the solution to this problem and you can write to me in discord to tell you
> My discord : 😈_DonJoan_😈#8207

I added you on discord and am looking for a solution to this
