### ISSUE TITLE
Change F2

### ISSUE THREAD

**Issue by SilvNobelen** [FrazzIe/rp-radio#44]
When i change the Hide button, then didn`t change the button into the menu..... 

There keep standing F2

![rp-radio](https://user-images.githubusercontent.com/60759015/106355475-75a39b80-62f8-11eb-8e5c-50f15c390451.PNG)

**Comment by FrazzIe** [comment]
Change the control name [here](https://github.com/FrazzIe/rp-radio/blob/master/rp-radio/config.lua#L4=)
