### ISSUE TITLE
RP Radio not working

### ISSUE THREAD

**Issue by blackdxdev** [FrazzIe/rp-radio#48]
Hello i got a problem with RP radio, im using the newest mumble voip version, i got no errors but /radio is not working.

**Comment by shalom69420** [comment]
i have the same problem

**Comment by Natesept26** [comment]
any solutions?

**Comment by NoNoTheGoat** [comment]
Client.lua 
Turn "Local Radio = {
        Has =True
______________________________
local Radio = {
	Has = false,
By default ^^^
______________________________
local Radio = {
	Has = true,
Fixed^^^

**Comment by Mattyice12226** [comment]
didnt work
