### ISSUE TITLE
Player names

### ISSUE THREAD

**Issue by HalfDollar** [FrazzIe/rp-radio#50]
How do I add instead of the list of random names where it says the players steam name

**Comment by mako00x01** [comment]
BUMP I wanna it to!

**Comment by RedactedStrix** [comment]
Or discord Names, using the Badger_Discord_API

**Comment by FrazzIe** [comment]
If you are referring to the radio list:
![Radio list image](https://camo.githubusercontent.com/d44ce51d70e13f3ed854d4a8a5560f184d4d9d0bdda8e71e0eb68bbe26ccb607/68747470733a2f2f692e696d6775722e636f6d2f306c71775430432e706e67)

It has nothing to do with the rp-radio script, it's part of my other resource: https://github.com/FrazzIe/mumble-voip-fivem

You can set player names on the list using this `server-side` export: https://github.com/FrazzIe/mumble-voip-fivem/blob/master/server.lua#L145

Example usage (Lua):

```lua
exports["mumble-voip"]:SetPlayerRadioName(  (Player server id), "Custom name")
```

**Comment by tyler4435** [comment]
how do i set it up to pull steam names
