### ISSUE TITLE
Theres no radio effects, can you add some ?

### ISSUE THREAD

**Issue by thatguycjames** [FrazzIe/rp-radio#53]

**Comment by P4R4NORM4L** [comment]
I just doesn't work

**Comment by P4R4NORM4L** [comment]
there are you just didn't set it up correctly

**Comment by P4R4NORM4L** [comment]
client.lua line #\2 change to true
restart resource and type in chat /radio

**Comment by FFMRLUCAS** [comment]
hey cant i change the sound when someone is talking in rp-radio
