### ISSUE TITLE
Change text on F2 menu

### ISSUE THREAD

**Issue by offshorejoe72** [FrazzIe/rp-radio#55]
Please advise on how to update text on the display window to change from F2 to F3?   unable to find in any of the files.

**Comment by FrazzIe** [comment]
https://github.com/FrazzIe/rp-radio/blob/master/rp-radio/config.lua#L4 change it to `INPUT_SAVE_REPLAY_CLIP` or the name of the control (I'm assuming 170 for F3) https://docs.fivem.net/docs/game-references/controls/
